version: '3.2'

services:
  nginx:
    image: nginx
    container_name: nginx_service
    restart: always
    volumes:
      - type: volume
        source: static_volume
        target: /static
      - type: bind
        source: ./.conf/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - web_service_network

  web:
    build:
      context: was_server/
      dockerfile: Dockerfile.prod
    volumes:
      - ./was_server/:/app/
      - static_volume:/.static_root/
    command: >
      bash -c "/prod_server_start.sh"      
    environment:
     - DEFAULT_HOST=${PROD_MYSQL_HOST}
     - DEFUALT_NAME=${PROD_MYSQL_DEV_DATABASE}
     - DEFAULT_USER=${PROD_MYSQL_USER}
     - DEFAULT_PASSWORD=${PROD_MYSQL_PASSWORD}
     - DFAULT_PORT=${PROD_MYSQL_PORT}
     - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    restart: always
    ports:
      - ${EXTERNAL_DJANGO_PORT}:8000
    networks:
      - web_service_network
  

  
networks: 
  web_service_network:
    driver: bridge

volumes: 
  static_volume:
