version: '3.2'

services:
  db:
    image: mysql:5.7
    container_name: mysql_service
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DEV_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - dev_db:/var/lib/mysql/
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "${EXTERNAL_MYSQL_PORT}:${MYSQL_PORT}"
    cap_add:
      - SYS_NICE 
    networks:
      - django_dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    command: >
      bash -c "/wait-for-db.sh db ${MYSQL_PORT} ${MYSQL_ROOT_PASSWORD} && /django_start.sh"
    environment:
     - DEFAULT_HOST=mysql_service
     - DEFUALT_NAME=${MYSQL_DEV_DATABASE}
     - DEFAULT_USER=${MYSQL_USER}
     - DEFAULT_PASSWORD=${MYSQL_PASSWORD}
     - DFAULT_PORT=${MYSQL_PORT}
     - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    restart: always
    ports:
      - ${EXTERNAL_DJANGO_PORT}:8000
    networks:
      - django_dev
  

  
networks: 
  django_dev:
    driver: bridge

volumes: 
  dev_db:
